### ISSUE TITLE
Serenity report does not display examples` values in Scenario outlines titles

### ISSUE THREAD

**Issue by jakimcho** [serenity-bdd/serenity-cucumber#138]
Hello,
Moved  [issue 1188](https://github.com/serenity-bdd/serenity-core/issues/1188)  here.

I have a cucumber feature file with a scenario outline that has examples placeholders in its title:

```
@sanity-check
  Scenario Outline: Player tries to complete Personal details form with <validation_type> in the <field>
    When the player completes Personal details form on Buy Credits page:
      | title   | first_name   | last_name   | date_of_birth   |
      | <title> | <first_name> | <last_name> | <date_of_birth> |
    Then validation "<validation_massage>" for "<field>" should appear on Personal details form

    Examples:
      | validation_type    | field         | title | first_name        | last_name                 | date_of_birth | validation_massage                      |
      | blank field        | title         |       | Automation        | Automation                | 02-27-1995    | This field is required                  |
      | numeric characters | first name    | Mr    | Automation1       | Automation                | 02-27-1995    | Please enter only alphabetic characters |
      .............................
      .............................
      .............................
```

My **expectation** is to have more descriptive scenarios titles for each scenario outline run in the report. Something like the one I get in cucumber report:

![cucumber_html](https://user-images.githubusercontent.com/6280772/38196339-1f6271c0-368b-11e8-959a-f44b98167e68.PNG)
The examples placeholders in scenario titles are populated with the values from the examples table

But in the **actual** serenity report I'm getting:
![serenity_report](https://user-images.githubusercontent.com/6280772/38196353-413dceb6-368b-11e8-9b52-436ba6b07268.PNG)
The examples placeholders in scenario titles are **not** populated with the values from the examples table

I'm using `serenity-core`, `serenity-cucumber` and `serenity-maven-plugin` versions - `1.9.4`

**Comment by wakaleo** [comment]
Feel free to make a PR, but I don't think this is an easy thing to do.

**Comment by wakaleo** [comment]
This should work now.

**Comment by krishnapemmaraju** [comment]
This is still not working , could you please suggest which version of serenity need to be used

**Comment by wakaleo** [comment]
2.3.12

**Comment by krishnapemmaraju** [comment]
Still facing issue , I have update pom xml with this verison

**Comment by wakaleo** [comment]
Can you put a screenshot of what you see and a copy of your feature file?

**Comment by krishnapemmaraju** [comment]
Thanks for the Reply 

![image](https://user-images.githubusercontent.com/53334205/105527512-b2113f00-5cdb-11eb-8c2f-09f8429a4712.png)

**Comment by krishnapemmaraju** [comment]
Feature File 

Feature: Sample Test Feautre for Report

  
  Scenario Outline: Title of your scenario outline is <name>
    Given I want to write a step with <name>
    When I check for the <value> in step
    Then I verify the <status> in step

    Examples: 
      | name  | value | status  |
      | name1 |     5 | success |
      | name2 |     7 | Fail    |

**Comment by wakaleo** [comment]
What behaviour are you expecting?

**Comment by krishnapemmaraju** [comment]
![image](https://user-images.githubusercontent.com/53334205/105527677-ef75cc80-5cdb-11eb-84bf-a108a5217184.png)

**Comment by krishnapemmaraju** [comment]
I am expecting
 Title of your scenario outline is name1

**Comment by wakaleo** [comment]
The title reflects what you write in the feature file. This looks like normal behaviour.

**Comment by krishnapemmaraju** [comment]
But the name is not getting replaced with the parameter value

**Comment by wakaleo** [comment]
It's the title of the scenario outline. If you put a variable placeholder, that's what will appear. You have 2 examples, how would Serenity know which one it should use for the title?

**Comment by krishnapemmaraju** [comment]
ok , if I am having only one example for each scenario like 

![image](https://user-images.githubusercontent.com/53334205/105528647-24ceea00-5cdd-11eb-8678-ce7a021a02a9.png)

**Comment by wakaleo** [comment]
That's just not the way the Serenity reporting works, under no circumstances will there be any variable substitution in a scenario outline heading.

**Comment by krishnapemmaraju** [comment]
thank you... what about the steps in Given and When 
![image](https://user-images.githubusercontent.com/53334205/105528959-8bec9e80-5cdd-11eb-937e-e5b26d209a6a.png)

**Comment by wakaleo** [comment]
It's the same principle - in a scenario outline, it makes no sense to insert any particular value into the text.

**Comment by krishnapemmaraju** [comment]
I gone through some PR with the same issue and I saw it some fix has been provided for this issue

**Comment by wakaleo** [comment]
It's not an issue, this is the correct, expected, and normal behaviour. That defect is referring to something else (the tags were not being rendered)

**Comment by krishnapemmaraju** [comment]
Thank you for your Quick Response..
